version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network  

  notification-service:
    container_name: notification-service
    image: jitheshmjithooz/notification-service
    build: ./notification-service
    restart: unless-stopped
    ports:
      - "3000:3000"  
    networks:
      - app-network  
    depends_on:
      - redis
    env_file:
      - ./notification-service/.env
    develop:
      watch:
        - action: sync
          path: ./notification-service
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./notification-service/package.json


  frontend-service:
    container_name: frontend-service
    image: jitheshmjithooz/frontend-service
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173"  
    networks:
      - app-network
    env_file:
      - ./frontend/.env
    depends_on:
      - notification-service
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

networks:
  app-network:
    driver: bridge 
